### PR TITLE
Readme improved

### PR DESCRIPTION
**Pull request by cutiko**
1. Brief explanation about name space "app" for xml
2. Float value is explained to be use in attr
3. Material design example added

### CODE REVIEW

**Comment by kyleduo** [comment]
Thanks for your work which let me know Readme.md has a lot to be improved. But I think you should check the demo app more and you will find a way which is more convenient and elegant  to achieve your style.

**Comment by cutiko** [comment]
Greetings

I checked the demo app, but didnt saw the source code, so I will do it
thanks.

Dont you want to at least accept the commits where I add the "app" name
space explanation?

Sorry if I wasnt helpfull :(

**Comment by kyleduo** [comment]
The namespace is a basic point of using layout xml file, and I think it should not in a library readme. But I'll add the `float` description to attributes part. Thanks for your remind and pull request.

**Comment by cutiko** [comment]
Im glad to help, at least a bit :) When I become a better developer I will
fork more important issues, thanks for your patience

**Pull request closed without merging**
